# Generated by Django 4.2.2 on 2024-03-13 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('faculty', models.CharField(choices=[('BIT', 'Bachelor of Information Technology'), ('BTECH', 'Bachelor of Technology'), ('CIVIL', 'Civil Engineering'), ('BBA', 'Bachelor of Business Administration')], max_length=20)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('BIT', 'Bachelor of Information Technology'), ('BTECH', 'Bachelor of Technology'), ('CIVIL', 'Civil Engineering'), ('BBA', 'Bachelor of Business Administration')], max_length=10)),
                ('id_no', models.CharField(choices=[('1111', '1111'), ('2222', '2222'), ('3333', '3333'), ('4444', '4444')], max_length=4)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
            ],
        ),
    ]
